server:
  error:
    include-stacktrace: never
  port: 8082
  
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/car_database?useTimezone=true&serverTimezone=UTC
    username: root
    password: Godblessyou_forever1@#
  
  main:
    allow-circular-references: true
    
  open-in-view: disable
   
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false  

      
api:
  security:
    token:
      secret: 1234567
      
flyway: 
  url: jdbc:mysql://localhost:3306/
  schemas: car_database
  user: root
  password: Godblessyou_forever1@#
  
springdoc:
  use-management-port: true
  show-actuator: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    
management:
  endpoints:
    web:
      exposure:
        include:  "*"
              
      cors:
        allowed-headers:
        - "*"
        allowed-origins:
        - "*"
        allowed-methods:
        - "*"
        allow-credentials: false
        
  server:
    port: 8085
    
  endpoint:
    shutdown:
      enabled: true
    


      